#!/usr/bin/env bash
#
# sync-ide.sh — generate kolang-ide's languages/kolang/docs.js from kolang-docs.json
#
# Reads the canonical kolang-docs.json and emits a docs.js ES module — a Map of
# identifier → Persian doc string (the format kolang-ide consumes for hover
# docs) — to STDOUT. Redirect stdout to overwrite
# kolang-ide/languages/kolang/docs.js. Usage notes go to stderr so stdout stays
# a clean, redirectable docs.js.
#
# Usage:
#   ./scripts/sync-ide.sh > ../kolang-ide/languages/kolang/docs.js

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
DATA_FILE="$ROOT_DIR/kolang-docs.json"

if [ ! -f "$DATA_FILE" ]; then
  echo "error: canonical data file not found: $DATA_FILE" >&2
  exit 1
fi

node -e '
const fs = require("fs");

const file = process.argv[1];
const data = JSON.parse(fs.readFileSync(file, "utf8"));

// Section order in the generated docs.js mirrors the original file: keywords,
// error classes, predefined functions (verbs → builtins → types), modules,
// then constant values.
const ORDER = ["keywords", "exceptions", "verbs", "builtins", "types", "modules", "literals"];

const CATEGORY_COMMENTS = {
  keywords: "کلمات کلیدی",
  exceptions: "کلاس‌های خطا",
  verbs: "افعال امری",
  builtins: "توابع از پیش‌تعریف‌شده",
  types: "نوع‌های داده",
  modules: "نام ماژول‌ها",
  literals: "مقادیر ثابت",
};

// Single-quoted JS string literal (matches the original docs.js style).
function sq(s) {
  return "\u0027" + s.replace(/\\/g, "\\\\").replace(/\u0027/g, "\\\u0027") + "\u0027";
}

const lines = [];
lines.push("// languages/kolang/docs.js — hover documentation data for Kolang.");
lines.push("//");
lines.push("// GENERATED by kolang-data/scripts/sync-ide.sh from kolang-docs.json —");
lines.push("// the canonical source lives in the kolang-data repo. Do not edit by");
lines.push("// hand; edit kolang-docs.json there and re-run the sync script.");
lines.push("//");
lines.push("// A Map of identifier → Persian doc string, consumed by the hover tooltip");
lines.push("// extension (languages/hover-docs.js, wired in renderer.js buildExtensions).");
lines.push("// Keys must match the identifiers exactly as they appear in code — note the");
lines.push("// ZWNJ (U+200C, نیم‌فاصله) inside compound identifiers like «خطای‌صفر»,");
lines.push("// «بسته‌است», «سیستم‌عامل».");
lines.push("");
lines.push("export const kolangDocs = new Map([");

for (const cat of ORDER) {
  const entries = data[cat];
  if (!entries || entries.length === 0) continue;
  lines.push("");
  lines.push("  // ---------------------------------------------------------------------------");
  lines.push("  // " + CATEGORY_COMMENTS[cat]);
  lines.push("  // ---------------------------------------------------------------------------");
  for (const [key, doc] of entries) {
    lines.push("  [" + sq(key) + ", " + sq(doc) + "],");
  }
}
lines.push("])");

process.stdout.write(lines.join("\n") + "\n");
' "$DATA_FILE"

cat >&2 <<EOF

✓ docs.js generated from kolang-docs.json (on stdout).
  Copy it into kolang-ide:
    ./scripts/sync-ide.sh > ../kolang-ide/languages/kolang/docs.js
EOF